### ISSUE TITLE
live2d 开启后生成静态文件报错

### ISSUE THREAD

**Issue by Zchengtui** [ochukai/hexo-theme-ochuunn#10]
详细报错信息：
```
Unhandled rejection TypeError: /home/zacco/Blog/themes/ochuunn/layout/_views/foot.pug:18
    16| if theme.live2d && !env.debug
    17|   canvas#live2dcanvas(width="400", height="800", class="live2d")
  > 18|   != live2d("live2dcanvas")
    19| 
    20| block foot
    21| 

live2d is not a function
    at eval (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:394:46)
    at template (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:397:72)
    at _compiled (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/zacco/Blog/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/home/zacco/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/zacco/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/zacco/Blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection TypeError: /home/zacco/Blog/themes/ochuunn/layout/_views/foot.pug:18
    16| if theme.live2d && !env.debug
    17|   canvas#live2dcanvas(width="400", height="800", class="live2d")
  > 18|   != live2d("live2dcanvas")
    19| 
    20| block foot
    21| 

live2d is not a function
    at eval (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:394:46)
    at template (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:397:72)
    at _compiled (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/zacco/Blog/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/home/zacco/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/zacco/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/zacco/Blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection TypeError: /home/zacco/Blog/themes/ochuunn/layout/_views/foot.pug:18
    16| if theme.live2d && !env.debug
    17|   canvas#live2dcanvas(width="400", height="800", class="live2d")
  > 18|   != live2d("live2dcanvas")
    19| 
    20| block foot
    21| 

live2d is not a function
    at eval (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:350:46)
    at template (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:353:72)
    at _compiled (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/zacco/Blog/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/home/zacco/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/zacco/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/zacco/Blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection TypeError: /home/zacco/Blog/themes/ochuunn/layout/_views/foot.pug:18
    16| if theme.live2d && !env.debug
    17|   canvas#live2dcanvas(width="400", height="800", class="live2d")
  > 18|   != live2d("live2dcanvas")
    19| 
    20| block foot
    21| 

live2d is not a function
    at eval (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:350:46)
    at template (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:353:72)
    at _compiled (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/zacco/Blog/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/home/zacco/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/zacco/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/zacco/Blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection TypeError: /home/zacco/Blog/themes/ochuunn/layout/_views/foot.pug:18
    16| if theme.live2d && !env.debug
    17|   canvas#live2dcanvas(width="400", height="800", class="live2d")
  > 18|   != live2d("live2dcanvas")
    19| 
    20| block foot
    21| 

live2d is not a function
    at eval (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:350:46)
    at template (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:353:72)
    at _compiled (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/zacco/Blog/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/home/zacco/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/zacco/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/zacco/Blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection TypeError: /home/zacco/Blog/themes/ochuunn/layout/_views/foot.pug:18
    16| if theme.live2d && !env.debug
    17|   canvas#live2dcanvas(width="400", height="800", class="live2d")
  > 18|   != live2d("live2dcanvas")
    19| 
    20| block foot
    21| 

live2d is not a function
    at eval (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:363:46)
    at template (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:366:72)
    at _compiled (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/zacco/Blog/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/home/zacco/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/zacco/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/zacco/Blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection TypeError: /home/zacco/Blog/themes/ochuunn/layout/_views/foot.pug:18
    16| if theme.live2d && !env.debug
    17|   canvas#live2dcanvas(width="400", height="800", class="live2d")
  > 18|   != live2d("live2dcanvas")
    19| 
    20| block foot
    21| 

live2d is not a function
    at eval (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:363:46)
    at template (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:366:72)
    at _compiled (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/zacco/Blog/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/home/zacco/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/zacco/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/zacco/Blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection TypeError: /home/zacco/Blog/themes/ochuunn/layout/_views/foot.pug:18
    16| if theme.live2d && !env.debug
    17|   canvas#live2dcanvas(width="400", height="800", class="live2d")
  > 18|   != live2d("live2dcanvas")
    19| 
    20| block foot
    21| 

live2d is not a function
    at eval (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:363:46)
    at template (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:366:72)
    at _compiled (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/zacco/Blog/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/home/zacco/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/zacco/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/zacco/Blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection TypeError: /home/zacco/Blog/themes/ochuunn/layout/_views/foot.pug:18
    16| if theme.live2d && !env.debug
    17|   canvas#live2dcanvas(width="400", height="800", class="live2d")
  > 18|   != live2d("live2dcanvas")
    19| 
    20| block foot
    21| 

live2d is not a function
    at eval (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:363:46)
    at template (eval at wrap (/home/zacco/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:366:72)
    at _compiled (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/zacco/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/zacco/Blog/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/home/zacco/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/zacco/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/zacco/Blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Zchengtui** [comment]
还有一个问题,关键词在哪设置..

**Comment by ochukai** [comment]
live2d 那个要安装 
```
npm install -save hexo-helper-live2d
```

**Comment by ochukai** [comment]
关键词还没有抽离出来,我一会儿改一下~

**Comment by ochukai** [comment]
![tim 20170531113847](https://cloud.githubusercontent.com/assets/2998925/26614900/c523f624-45f5-11e7-9ed6-25a615c1c2fd.jpg)
全局可以这么设置, 每一篇文章的设置暂时还没有~

**Comment by Zchengtui** [comment]
OK
